[build]
  cmd = "templ generate && go build -mod=mod -buildvcs=false -o ./tmp/hakken ./cmd/hakken"
  bin = "./tmp/hakken"
  full_bin = "./tmp/hakken"
  include_ext = ["go", "templ"]
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_templ\\.go$"]
  delay = 1000
  kill_delay = "500ms"
  rerun = false
  log = "build-errors.log"

[log]
  time = false

[color]
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
