// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/xblackbytesx/tabidachi/web/templates/layouts"

func TripNew(csrfToken string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"page-header\"><a href=\"/\" class=\"btn btn-ghost btn-sm\"><wa-icon name=\"arrow-left\"></wa-icon> Back</a><h1 class=\"page-title\">New Trip</h1></div><p class=\"page-subtitle\">How would you like to create your itinerary?</p><div class=\"method-grid\"><a href=\"/trips/new/scratch\" class=\"method-card\"><wa-icon name=\"pen-to-square\" class=\"method-icon\"></wa-icon><h2 class=\"method-title\">Build manually</h2><p class=\"method-desc\">Create your trip step by step — add legs, days, and events by hand.</p></a> <a href=\"/trips/new/import\" class=\"method-card\"><wa-icon name=\"file-code\" class=\"method-icon\"></wa-icon><h2 class=\"method-title\">Import JSON</h2><p class=\"method-desc\">Paste or upload a JSON itinerary following the Tabidachi schema.</p></a> <a href=\"/trips/new/convert\" class=\"method-card\"><wa-icon name=\"arrows-rotate\" class=\"method-icon\"></wa-icon><h2 class=\"method-title\">Convert existing itinerary</h2><p class=\"method-desc\">Have a booking doc, email, or spreadsheet? We'll generate an AI prompt to convert it to Tabidachi JSON.</p></a> <a href=\"/trips/new/plan\" class=\"method-card method-card-featured\"><wa-icon name=\"wand-magic-sparkles\" class=\"method-icon\"></wa-icon><h2 class=\"method-title\">Plan with AI</h2><p class=\"method-desc\">Describe where you want to go — AI builds a personalised itinerary prompt for you.</p><span class=\"method-badge\">Recommended</span></a></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base("New Trip", csrfToken).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
